# Notes on Chapter 13 of *Hands-On Machine Learning with Scikit-Learn, Keras, & TensorFlow*, 3rd edition, by Aurélien Géron

Reduce the amount of logging messages displayed by TensorFlow

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

In [34]:
import itertools
from pathlib import Path
import time

import keras
from keras import layers
from matplotlib import pyplot as plt
import numpy as np
import seaborn as sns
import tensorflow as tf
import tensorflow.experimental.numpy as tnp

Datasets are iterable sequences of data items

In [27]:
X = {"a" : tf.reshape(tf.range(9.), (3,3)), "b": tf.range(100.,103)}

dataset = tf.data.Dataset.from_tensor_slices(X)
for x in dataset:
    print(x)

{'a': <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 1., 2.], dtype=float32)>, 'b': <tf.Tensor: shape=(), dtype=float32, numpy=100.0>}
{'a': <tf.Tensor: shape=(3,), dtype=float32, numpy=array([3., 4., 5.], dtype=float32)>, 'b': <tf.Tensor: shape=(), dtype=float32, numpy=101.0>}
{'a': <tf.Tensor: shape=(3,), dtype=float32, numpy=array([6., 7., 8.], dtype=float32)>, 'b': <tf.Tensor: shape=(), dtype=float32, numpy=102.0>}


Multiple transformations can be chained together on datasets

In [33]:
dataset2 = dataset.repeat(3).map(
        lambda x: {'c':x['a']+0.1+x['b'], 'd':2*x['b']}
    ).shuffle(buffer_size=5, seed=13).batch(4)
for x in dataset2:
    print(x)

{'c': <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[108.1, 109.1, 110.1],
       [104.1, 105.1, 106.1],
       [100.1, 101.1, 102.1],
       [104.1, 105.1, 106.1]], dtype=float32)>, 'd': <tf.Tensor: shape=(4,), dtype=float32, numpy=array([204., 202., 200., 202.], dtype=float32)>}
{'c': <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[100.1, 101.1, 102.1],
       [100.1, 101.1, 102.1],
       [108.1, 109.1, 110.1],
       [104.1, 105.1, 106.1]], dtype=float32)>, 'd': <tf.Tensor: shape=(4,), dtype=float32, numpy=array([200., 200., 204., 202.], dtype=float32)>}
{'c': <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[108.1, 109.1, 110.1]], dtype=float32)>, 'd': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([204.], dtype=float32)>}


In [ ]:
dataset.shuffle(